<a href="https://colab.research.google.com/github/Anuragkar234/pytorch/blob/master/Pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
w=torch.tensor(2.0,requires_grad=True)
b=torch.tensor(-1.0,requires_grad=True)

def forward(x):
  y=w*x+b
  return y

x=torch.tensor([[1.0]])

yhat=forward(x)
yhat


tensor([[1.]], grad_fn=<AddBackward0>)

In [ ]:
import torch
w=torch.tensor(2.0,requires_grad=True)
b=torch.tensor(-1.0,requires_grad=True)

def forward(x):
  y=w*x+b
  return y

x=torch.tensor([[1],[2]])  # first one rows and second one columns

yhat=forward(x)
yhat


tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)

In [ ]:
from torch.nn import Linear
model = Linear(in_features = 1, out_features = 1)
y = model(x)

RuntimeError: ignored

In [13]:
from torch.nn import Linear 
torch.manual_seed(1)
model = Linear(in_features = 1, out_features =1)
print(list (model.parameters()))

# Part of this context is not fully understood!!

x = torch.tensor([[0.0]])
yhat = model(x)
yhat

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


tensor([[-0.4414]], grad_fn=<AddmmBackward>)

In [14]:
from torch.nn import Linear 

x = torch.tensor([[1.0],[2.0]])

yhat = model(x)
yhat

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)

In [25]:
# Using custom Modules in pytorch

import torch.nn as nn

class LR(nn.Module):
  def __init__(self, in_size, out_size):
    # supper(LR,self).__init__()
    nn.Module.__init__(self)
    self.linear = nn.Linear(in_size, out_size)
  
  def forward(self, x):
    out = self.linear(x)
    return out

model = LR(1,1)
print(list(model.parameters()))

x = torch.tensor([[1.0]])
yhat = model(x)

print(yhat)

[Parameter containing:
tensor([[-0.0729]], requires_grad=True), Parameter containing:
tensor([-0.0900], requires_grad=True)]
tensor([[-0.1629]], grad_fn=<AddmmBackward>)


In [26]:
# Using custom Modules in pytorch
# Rechecking the module e=unexpected behaviour
import torch.nn as nn

class LR(nn.Module):
  def __init__(self, in_size, out_size):
    # supper(LR,self).__init__()
    nn.Module.__init__(self)
    self.linear = nn.Linear(in_size, out_size)
  
  def forward(self, x):
    out = self.linear(x)
    return out

model = LR(1,1)
print(list(model.parameters()))

x = torch.tensor([[1.0]])
yhat = model(x)

print(yhat)

[Parameter containing:
tensor([[0.1449]], requires_grad=True), Parameter containing:
tensor([-0.0040], requires_grad=True)]
tensor([[0.1409]], grad_fn=<AddmmBackward>)
